import { createHash } from 'node:crypto'
import { ApiError } from '../errors'
import type { Store } from '../workspace/store'
import type { Flow } from './model'
import type { BackendCodeArtifact } from './backend-code-model'
import { validateFlow } from './engine'
import { graphqlSchema } from './graphql'
import { flowTransport } from './transport'

export const backendCompilerVersion = 2

function literal(value: string) {
  return `'${value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')}'`
}

const hash = (value: string) => createHash('sha256').update(value).digest('hex')

export function generateBackendCode(
  flowId: string,
  revision: number,
  definition: Flow,
): BackendCodeArtifact {
  return renderBackendCode(flowId, revision, definition, backendCompilerVersion)
}

function renderBackendCode(
  flowId: string,
  revision: number,
  definition: Flow,
  compilerVersion: number,
): BackendCodeArtifact {
  definition = validateFlow(definition)
  if (definition.graphql) graphqlSchema(definition)
  const transport = flowTransport(definition)
  if (compilerVersion === 1 && transport === 'websocket')
    throw new ApiError(
      503,
      'Published backend artifact failed integrity validation',
    )
  const graphql = Boolean(definition.graphql)
  const endpoint = {
    method: definition.method,
    path: `${transport === 'websocket' ? '/ws' : graphql ? '/graphql' : '/run'}${definition.path}`,
    graphql,
    ...(compilerVersion === 2 ? { transport } : {}),
  }
  const snapshot = JSON.stringify({ flowId, revision, definition })
  const code = `// Generated by Besh backend compiler ${compilerVersion}
// Requires Besh runtime helpers. This module is not a standalone server.
module.exports = function register(app, runtime, generation) {
  const release = JSON.parse(${literal(snapshot)})

${
  transport === 'websocket'
    ? `  app.ws(${literal(endpoint.path)}, runtime.websocket(release, generation))

  for (const method of ['GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'])
    app.route(method, ${literal(endpoint.path)}, ({ request }) =>
      runtime.websocketHttp(release, generation, request))

  app.route('POST', ${literal(endpoint.path + '/ticket')}, ({ request, body }) =>
    runtime.websocketTicket(release, generation, request, body))`
    : `  app.route(${literal(endpoint.method)}, ${literal(endpoint.path)}, ({ request, body, query }) =>
    runtime.${graphql ? 'graphql' : 'rest'}(release, generation, request, body, query))`
}
${
  graphql
    ? `
  for (const method of ['GET', 'HEAD', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'])
    app.route(method, ${literal(endpoint.path)}, ({ request }) =>
      runtime.graphqlMethod(release, generation, request))
`
    : ''
}
  return app
}
`
  if (Buffer.byteLength(code) > 1_048_576)
    throw new ApiError(400, 'Generated backend code exceeds its size limit')
  return {
    flowId,
    revision,
    compilerVersion,
    filename: `besh-${flowId}-r${revision}.cjs`,
    code,
    sha256: hash(code),
    definitionSha256: hash(JSON.stringify(definition)),
    endpoint,
    requirements: [
      'Besh runtime helpers and the matching backend compiler version are required.',
      'Register this generated module through Besh; it is not a standalone server.',
      'Referenced data and credentials remain server-managed and are not bundled.',
    ],
  }
}

export function verifyBackendCode(
  store: Store,
  artifact: BackendCodeArtifact,
  definition: Flow,
  requireCurrent = false,
) {
  const records = store
    .query<
      {
        compiler_version: number
        source: string
        sha256: string
        definition_sha256: string
      },
      [string, number]
    >(
      'SELECT compiler_version, source, sha256, definition_sha256 FROM backend_artifacts WHERE flow_id = ? AND revision = ?',
    )
    .all(artifact.flowId, artifact.revision)
  if (
    requireCurrent &&
    !records.some((row) => row.compiler_version === backendCompilerVersion)
  )
    throw new ApiError(
      503,
      'Published backend artifact failed integrity validation',
    )
  for (const row of records) {
    if (
      row.compiler_version !== 1 &&
      row.compiler_version !== backendCompilerVersion
    )
      throw new ApiError(
        503,
        'Published backend artifact failed integrity validation',
      )
    const trusted =
      row.compiler_version === backendCompilerVersion
        ? artifact
        : renderBackendCode(artifact.flowId, artifact.revision, definition, 1)
    if (
      row.source !== trusted.code ||
      row.sha256 !== trusted.sha256 ||
      row.definition_sha256 !== trusted.definitionSha256
    )
      throw new ApiError(
        503,
        'Published backend artifact failed integrity validation',
      )
  }
}

export function saveBackendCode(store: Store, artifact: BackendCodeArtifact) {
  const existing = store
    .query<
      { source: string; sha256: string; definition_sha256: string },
      [string, number, number]
    >(
      'SELECT source, sha256, definition_sha256 FROM backend_artifacts WHERE flow_id = ? AND revision = ? AND compiler_version = ?',
    )
    .get(artifact.flowId, artifact.revision, artifact.compilerVersion)
  if (
    existing &&
    (existing.source !== artifact.code ||
      existing.sha256 !== artifact.sha256 ||
      existing.definition_sha256 !== artifact.definitionSha256)
  )
    throw new ApiError(
      503,
      'Published backend artifact failed integrity validation',
    )
  store
    .query(
      'INSERT OR IGNORE INTO backend_artifacts (flow_id, revision, compiler_version, source, sha256, definition_sha256) VALUES (?, ?, ?, ?, ?, ?)',
    )
    .run(
      artifact.flowId,
      artifact.revision,
      artifact.compilerVersion,
      artifact.code,
      artifact.sha256,
      artifact.definitionSha256,
    )
}

export function currentBackendCode(
  store: Store,
  id: string,
  revision?: number,
) {
  return store.db.transaction(() => {
    const row = store
      .query<
        { published: string | null; published_revision: number | null },
        [string]
      >('SELECT published, published_revision FROM flows WHERE id = ?')
      .get(id)
    if (!row) throw new ApiError(404, 'Flow not found')
    if (!row.published || row.published_revision === null)
      throw new ApiError(404, 'This API has no published release')
    if (revision !== undefined && revision !== row.published_revision)
      throw new ApiError(
        409,
        'Published release changed. Reload before reading backend code.',
      )
    const definition = JSON.parse(row.published)
    const artifact = generateBackendCode(id, row.published_revision, definition)
    verifyBackendCode(store, artifact, definition, true)
    return artifact
  })()
}
