export const collectionRendererLanguages = [
  {
    code: 'en',
    choice: 'English',
    heading: 'Collection HTML settings',
    save: 'Save HTML settings',
    reload: 'Reload HTML settings',
    defaults: 'Use default settings',
    classes: 'CSS classes',
    title: 'Title attribute',
    aria: 'Accessibility label',
    fixed: 'Use fixed heading identifier',
  },
  {
    code: 'th',
    choice: 'ไทย',
    heading: 'การตั้งค่า HTML ของคอลเลกชัน',
    save: 'บันทึกการตั้งค่า HTML',
    reload: 'โหลดการตั้งค่า HTML อีกครั้ง',
    defaults: 'ใช้การตั้งค่าเริ่มต้น',
    classes: 'คลาส CSS',
    title: 'แอตทริบิวต์ title',
    aria: 'ป้ายกำกับสำหรับการเข้าถึง',
    fixed: 'ใช้ตัวระบุหัวเรื่องแบบตายตัว',
  },
  {
    code: 'zh',
    choice: '中文',
    heading: '集合 HTML 设置',
    save: '保存 HTML 设置',
    reload: '重新加载 HTML 设置',
    defaults: '使用默认设置',
    classes: 'CSS 类名',
    title: 'title 属性',
    aria: '无障碍标签',
    fixed: '使用固定标题标识符',
  },
  {
    code: 'ru',
    choice: 'Русский',
    heading: 'Настройки HTML коллекции',
    save: 'Сохранить настройки HTML',
    reload: 'Загрузить настройки HTML заново',
    defaults: 'Использовать настройки по умолчанию',
    classes: 'Классы CSS',
    title: 'Атрибут title',
    aria: 'Метка доступности',
    fixed: 'Использовать фиксированный идентификатор заголовка',
  },
  {
    code: 'ja',
    choice: '日本語',
    heading: 'コレクションの HTML 設定',
    save: 'HTML 設定を保存',
    reload: 'HTML 設定を再読み込み',
    defaults: '既定の設定を使用',
    classes: 'CSS クラス',
    title: 'title 属性',
    aria: 'アクセシビリティラベル',
    fixed: '固定の見出し識別子を使用',
  },
  {
    code: 'ko',
    choice: '한국어',
    heading: '컬렉션 HTML 설정',
    save: 'HTML 설정 저장',
    reload: 'HTML 설정 다시 불러오기',
    defaults: '기본 설정 사용',
    classes: 'CSS 클래스',
    title: 'title 속성',
    aria: '접근성 레이블',
    fixed: '고정 제목 식별자 사용',
  },
  {
    code: 'pt',
    choice: 'Português',
    heading: 'Configurações de HTML da coleção',
    save: 'Salvar configurações de HTML',
    reload: 'Recarregar configurações de HTML',
    defaults: 'Usar configurações padrão',
    classes: 'Classes CSS',
    title: 'Atributo title',
    aria: 'Rótulo de acessibilidade',
    fixed: 'Usar identificador fixo de título',
  },
] as const
